In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv',error_bad_lines=False)

C:\Users\Hp\AppData\Local\Temp\ipykernel_15280\3463374263.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv('data.csv',error_bad_lines=False)
b'Skipping line 2810: expected 2 fields, saw 5\nSkipping line 4641: expected 2 fields, saw 5\nSkipping line 7171: expected 2 fields, saw 5\nSkipping line 11220: expected 2 fields, saw 5\nSkipping line 13809: expected 2 fields, saw 5\nSkipping line 14132: expected 2 fields, saw 5\nSkipping line 14293: expected 2 fields, saw 5\nSkipping line 14865: expected 2 fields, saw 5\nSkipping line 17419: expected 2 fields, saw 5\nSkipping line 22801: expected 2 fields, saw 5\nSkipping line 25001: expected 2 fields, saw 5\nSkipping line 26603: expected 2 fields, saw 5\nSkipping line 26742: expected 2 fields, saw 5\nSkipping line 29702: expected 2 fields, saw 5\nSkipping line 32767: expected 2 fields, saw 5\nSkipping line 32878: expected 2 fields, 

b'Skipping line 525174: expected 2 fields, saw 5\nSkipping line 526251: expected 2 fields, saw 5\nSkipping line 529611: expected 2 fields, saw 5\nSkipping line 531398: expected 2 fields, saw 5\nSkipping line 534146: expected 2 fields, saw 5\nSkipping line 544954: expected 2 fields, saw 5\nSkipping line 553002: expected 2 fields, saw 5\nSkipping line 553883: expected 2 fields, saw 5\nSkipping line 553887: expected 2 fields, saw 5\nSkipping line 553915: expected 2 fields, saw 5\nSkipping line 554172: expected 2 fields, saw 5\nSkipping line 563534: expected 2 fields, saw 5\nSkipping line 565191: expected 2 fields, saw 5\nSkipping line 574108: expected 2 fields, saw 5\nSkipping line 574412: expected 2 fields, saw 5\nSkipping line 575985: expected 2 fields, saw 5\nSkipping line 580091: expected 2 fields, saw 5\nSkipping line 582682: expected 2 fields, saw 5\nSkipping line 585885: expected 2 fields, saw 5\nSkipping line 590171: expected 2 fields, saw 5\nSkipping line 591924: expected 2 field

In [3]:
df.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [4]:
df.shape

(669640, 2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669640 entries, 0 to 669639
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   password  669639 non-null  object
 1   strength  669640 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 10.2+ MB


In [6]:
df.isnull().sum()

password    1
strength    0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df["strength"] = df["strength"].map({0: "Weak", 
                                         1: "Medium",
                                         2: "Strong"})

In [9]:
df.head()

password strength
0     kzde5577   Medium
1     kino3434   Medium
2    visi7k1yr   Medium
3     megzy123   Medium
4  lamborghin1   Medium

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [13]:
pass_tup=np.array(df)

In [14]:
import random
random.shuffle(pass_tup)

In [15]:
x=[labels[0] for labels in pass_tup]
y=[labels[1] for labels in pass_tup]

In [16]:
x

['kzde5577',
 'kzde5577',
 'visi7k1yr',
 'kzde5577',
 'kzde5577',
 'lamborghin1',
 'visi7k1yr',
 'kzde5577',
 'u6c8vhow',
 'AVYq1lDE4MgAZfNt',
 'v1118714',
 'universe2908',
 'AVYq1lDE4MgAZfNt',
 'lamborghin1',
 'kzde5577',
 'jerusalem393',
 'jytifok873',
 'lamborghin1',
 'idofo673',
 'kzde5577',
 'WUt9IZzE0OQ7PkNE',
 'intel1',
 'kino3434',
 'visi7k1yr',
 'asv5o9yu',
 'intel1',
 'kino3434',
 'idofo673',
 'czuodhj972',
 'sbl571017',
 'jerusalem393',
 'czuodhj972',
 '6975038lp',
 'g067057895',
 'sbl571017',
 'faranumar91',
 '612035180tok',
 'go7kew7a2po',
 'asgaliu11',
 'asgaliu11',
 'klara-tershina3H',
 'pHyqueDIyNQ8vmhb',
 'fk9qi21m',
 'fahad123',
 '52558000aaa',
 'yitbos77',
 'go7kew7a2po',
 'cigicigi123',
 'elyass15@ajilent-ci',
 '6975038lp',
 'lamborghin1',
 'visi7k1yr',
 '0169395484a',
 'exitos2009',
 'yk530mg8',
 'c3h8bkzr',
 'calcifer32',
 'prisonbreak1',
 'kzde5577',
 'fk9qi21m',
 'memjan123',
 'AVYq1lDE4MgAZfNt',
 'memjan123',
 'AVYq1lDE4MgAZfNt',
 'lsdlsd1',
 'ok>bdk',
 'u6c8vh

In [20]:
def word_divider(words):
    char=[]
    for i in words:
        char.append(i)
    return char

In [22]:
print(word_divider('hello'))

['h', 'e', 'l', 'l', 'o']


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
vectorizer=TfidfVectorizer(tokenizer=word_divider)

In [25]:
X=vectorizer.fit_transform(x)

In [26]:
X.shape

(669639, 136)

In [27]:
first_document_vector=X[0]
first_document_vector

<1x136 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [28]:
first_document_vector.T.todense()


matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56661848],
        [0.        ],
        [0.59171402],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [29]:
df=pd.DataFrame(first_document_vector.T.todense(),index=vectorizer.get_feature_names(),columns=['TF-IDE'])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [31]:
df.sort_values(by=['TF-IDE'],ascending=False)

TF-IDE
7   0.591714
5   0.566618
z   0.335914
k   0.292120
d   0.285909
..       ...
=   0.000000
<   0.000000
;   0.000000
9   0.000000
™   0.000000

[136 rows x 1 columns]

In [32]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [33]:
rfc = RandomForestClassifier(n_estimators=10,criterion='entropy')

In [35]:
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [37]:
y_pred=rfc.predict(X_test)

In [38]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[123407    265    332]
 [  1023  19846     37]
 [  2380      3  20117]]
0.9758676303685563


In [58]:
def check(password):
    data = vectorizer.transform([password]).toarray()
    output = rfc.predict(data)
    return output

In [59]:
print(check("qwerty")[0])

Weak


In [61]:
print(check("svkm123")[0])

Medium


In [62]:
print(check("12345678")[0])

Medium


In [63]:
print(check("111111")[0])

Weak


In [65]:
print(check("sunshine")[0])

Medium


In [66]:
print(check("daddygamer@123")[0])

Strong
